@echo off
echo Locating project directory and running tests...

cd /d "c:\Users\aviad\OneDrive\Desktop\backv2"
echo Current directory is now: %CD%

echo Creating test results directory...
mkdir DevDocs\test-results 2>nul

echo Running tests from the correct location...
echo This may take a few minutes. Please wait...
cd DevDocs

echo Running simplified test first to verify setup...
npx playwright test tests/integration.spec.ts:81 --headed --timeout=30000

echo Running full integration tests...
echo Tests can take several minutes depending on server response times...
npx playwright test tests/integration.spec.ts --headed --timeout=60000

echo Opening test report...
npx playwright show-report

pause
