name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'DevDocs/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: github-456508
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authenticate Docker to Google Cloud
      run: gcloud auth configure-docker

    - name: Build and push DevDocs image
      run: |
        docker build -t me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-app:${{ github.sha }} -f ./DevDocs/frontend/Dockerfile ./DevDocs/frontend
        docker push me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-app:${{ github.sha }}

    - name: Build and push MCP server image
      run: |
        docker build -t me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-mcp-server:${{ github.sha }} -f ./DevDocs/Dockerfile.simple ./DevDocs
        docker push me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-mcp-server:${{ github.sha }}

    - name: Deploy DevDocs to Cloud Run
      run: |
        gcloud run deploy devdocs-app \
          --image me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-app:${{ github.sha }} \
          --region me-west1 \
          --platform managed \
          --allow-unauthenticated \
          --port=3002 \
          --command="npm" \
          --args="start" \
          --set-env-vars=NODE_ENV=production,PORT=3002,NEXT_PUBLIC_SUPABASE_URL=https://dnjnsotemnfrjlotgved.supabase.co,NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}

    - name: Deploy MCP server to Cloud Run
      run: |
        gcloud run deploy devdocs-mcp-server \
          --image me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-mcp-server:${{ github.sha }} \
          --region me-west1 \
          --platform managed \
          --allow-unauthenticated \
          --port=8080 \
          --command="node" \
          --args="server.js" \
          --set-env-vars=GOOGLE_CLOUD_PROJECT_ID=github-456508,MCP_API_KEY=${{ secrets.MCP_API_KEY }},PORT=8080,SUPABASE_URL=https://dnjnsotemnfrjlotgved.supabase.co,SUPABASE_KEY=${{ secrets.SUPABASE_ANON_KEY }}
