name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'DevDocs/**'
      - 'ai_feedback_learning.py'
      - 'ai_enhanced_processor.py'
      - 'web_interface.py'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: github-456508
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authenticate Docker to Google Cloud
      run: gcloud auth configure-docker

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd DevDocs/frontend
        npm install
        npm install @chakra-ui/react @emotion/react @emotion/styled framer-motion react-router-dom --save

    - name: Build frontend
      run: |
        cd DevDocs/frontend
        npm run build

    - name: Build and push DevDocs image
      run: |
        docker build -t me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-app:${{ github.sha }} -f ./DevDocs/frontend/Dockerfile ./DevDocs/frontend
        docker push me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-app:${{ github.sha }}

    - name: Build and push MCP server image
      run: |
        docker build -t me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-mcp-server:${{ github.sha }} -f ./DevDocs/Dockerfile.simple ./DevDocs
        docker push me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-mcp-server:${{ github.sha }}

    - name: Deploy DevDocs to Cloud Run
      run: |
        gcloud run deploy devdocs-app \
          --image me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-app:${{ github.sha }} \
          --region me-west1 \
          --platform managed \
          --allow-unauthenticated \
          --port=3002 \
          --command="serve" \
          --args="-s,out,-p,3002" \
          --set-env-vars=NODE_ENV=production,PORT=3002,NEXT_PUBLIC_SUPABASE_URL=https://dnjnsotemnfrjlotgved.supabase.co,NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}

    - name: Deploy MCP server to Cloud Run
      run: |
        gcloud run deploy devdocs-mcp-server \
          --image me-west1-docker.pkg.dev/github-456508/devdocs/devdocs-mcp-server:${{ github.sha }} \
          --region me-west1 \
          --platform managed \
          --allow-unauthenticated \
          --port=8080 \
          --command="node" \
          --args="server.js" \
          --set-env-vars=GOOGLE_CLOUD_PROJECT_ID=github-456508,MCP_API_KEY=${{ secrets.MCP_API_KEY }},PORT=8080,SUPABASE_URL=https://dnjnsotemnfrjlotgved.supabase.co,SUPABASE_KEY=${{ secrets.SUPABASE_ANON_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests python-dotenv pdfplumber

    - name: Build and push AI Enhanced Processor image
      run: |
        docker build -t me-west1-docker.pkg.dev/github-456508/devdocs/ai-enhanced-processor:${{ github.sha }} .
        docker push me-west1-docker.pkg.dev/github-456508/devdocs/ai-enhanced-processor:${{ github.sha }}

    - name: Deploy AI Enhanced Processor to Cloud Run
      run: |
        gcloud run deploy ai-enhanced-processor \
          --image me-west1-docker.pkg.dev/github-456508/devdocs/ai-enhanced-processor:${{ github.sha }} \
          --region me-west1 \
          --platform managed \
          --allow-unauthenticated \
          --port=8081 \
          --command="python3" \
          --args="web_interface.py" \
          --set-env-vars=GOOGLE_CLOUD_PROJECT_ID=github-456508,OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }},PORT=8081,SUPABASE_URL=https://dnjnsotemnfrjlotgved.supabase.co,SUPABASE_KEY=${{ secrets.SUPABASE_ANON_KEY }}
