name: Build and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'DevDocs/frontend/package.json'

    - name: Install frontend dependencies
      run: |
        cd DevDocs/frontend
        npm ci

    - name: Build frontend
      run: |
        cd DevDocs/frontend
        npm run build

    - name: Install backend dependencies
      run: |
        cd DevDocs/backend
        npm ci

    - name: Run frontend tests
      run: |
        cd DevDocs/frontend
        npm test || true

    - name: Run backend tests
      run: |
        cd DevDocs/backend
        npm test || true
